"""
This produces a plot of points against the fraction of those points that
were achieved from the bonus for getting all squares within a group.
"""

import pandas as pd

from monopoly import Monopoly


pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

monopoly = Monopoly()
monopoly.setup()

df = monopoly.places[["Place", "Square", "Value", "Group Name"]]
df.reset_index(inplace=True, names="Place ID")
df["Place ID"] = df["Place ID"].astype("object")
df.loc[0, "Place ID"] = "M"
caption = "The 2025 Monopoly Run places with their associated squares, groups, and values."
label = "tab:Places"
column_format = "c" * df.columns.size

latex = df.to_latex(
    index=False,
    column_format=column_format,
    caption=caption,
    label=label,
    longtable=True)

with open("../Essay/Data/Places.tex", "w+") as file:
    file.write("% Do not edit - this file was automatically generated by output_places\n\n")
    file.write(latex)
