"""
This produces the LaTeX for a table showing information about the places
for a given version of the Monopoly Run.
"""

import os

import pandas as pd

from monopoly import Monopoly


def main(name):
    print(f"Generating LaTeX table of places for {name}.")
    monopoly = Monopoly(name)
    monopoly.setup()
    places = get_places(monopoly)
    latex = get_latex(places)
    save(monopoly, latex)

def get_places(monopoly):
    places = monopoly.places[["Place", "Square", "Value", "Group Name"]]
    places.reset_index(inplace=True, names="Place ID")
    places["Place ID"] = places["Place ID"].astype("object")
    places.loc[0, "Place ID"] = monopoly.terminal[0]
    return places

def get_latex(places):
    caption = "The 2026 Monopoly Run places with their associated squares, groups, and values."
    label = "tab:Places"
    column_format = "c" * places.columns.size
    latex = places.to_latex(
        index=False,
        column_format=column_format,
        caption=caption,
        label=label,
        longtable=True)
    return latex

def save(monopoly, latex):
    path = os.path.join(monopoly.output_path, "Places.tex")
    with open(path, "w+") as file:
        file.write("% Do not edit - this file was automatically generated by output_places\n\n")
        file.write(latex)
