"""
This script produces the LaTeX for a table with information about which
groups were achieved at a given speed for a given version of the
Monopoly Run.
"""


import os

import numpy as np
import pandas as pd

from monopoly import Monopoly


def main(name):
    print(f"Generating LaTeX table which indicates which groups were achieved for {name}.")
    monopoly = Monopoly(name)
    monopoly.setup()
    monopoly.load()
    groups = get_groups(monopoly)
    add_line_breaks_to_headers(groups)
    latex = get_latex(groups)
    save(monopoly, latex)

def get_groups(monopoly):
    groups = monopoly.indicators.xs("Group", level=0)
    groups = groups.T
    groups.index.name = "Speed (m/s)"
    groups["Group Points"] = groups.dot(monopoly.groups["Value"].values).T
    groups = groups.drop(columns="Terminals")
    groups.columns.name = None
    groups["Points"] = monopoly.solutions["Points"].values
    groups = groups.reset_index()
    return groups

def add_line_breaks_to_headers(groups):
    names = {old_name: get_new_name(old_name) for old_name in groups.columns}
    groups.rename(columns=names, inplace=True)

def get_new_name(old_name):
    words = old_name.split(" ")
    if len(words) == 1:
        return old_name
    else:
        names = r" \\ ".join(words)
        return f"\\makecell{{{names}}}"

def get_latex(groups):
    column_format = "c" * groups.columns.size
    caption = "Which groups were achieved for each given speed."
    label = "tab:GroupResults"
    latex = groups.to_latex(
        index=False,
        float_format="{:.1f}".format,
        column_format=column_format,
        longtable=True,
        escape=False,
        caption=caption,
        label=label)
    return latex

def save(monopoly, latex):
    path = os.path.join(monopoly.output_path, "GroupResults.tex")
    with open(path, "w+") as file:
        file.writelines("% Do not edit: this has been automatically generated by output_groups.py\n\n")
        file.write(latex)
