"""
The purpose of this script is to take the generated output data and
produce a csv that summarises what groups were achieved at what speed.
"""


import os

import numpy as np
import pandas as pd

from monopoly import Monopoly


pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

monopoly = Monopoly()
monopoly.setup()
monopoly.load()

groups = monopoly.indicators.xs("Group", level=0)
groups = groups.T
groups.index.name = "Speed (m/s)"
groups["Group Points"] = groups.dot(monopoly.groups["Value"].values).T
groups = groups.drop(columns="Terminals")
groups.columns.name = None
groups.drop(columns=["Landmarks"], inplace=True)
groups["Points"] = monopoly.solutions["Points"].values
groups = groups.loc[groups.index <= 6.9]
groups = groups.reset_index()
column_format = "c" * groups.columns.size
caption = "Which groups were achieved for each given speed."
label = "tab:GroupResults"

latex = groups.to_latex(
    index=False,
    float_format="{:.1f}".format,
    column_format=column_format,
    longtable=True,
    escape=True,
    caption=caption,
    label=label)

with open("../Essay/Data/GroupResults.tex", "w+") as file:
    file.writelines("% Do not edit: this has been automatically generated by output_groups.py\n\n")
    file.write(latex)
